### ISSUE TITLE
Use Roku remote in a more native game controller way

### ISSUE THREAD

**Issue by bradleybossard** [lvcabral/Prince-of-Persia-Roku#1]
Pretty cool, like the work you've done here!

After installing, it seems like in order to play the game, you need to hold the Roku remote in the upright position and use the OK button for actions.  It would be more playable to hold the controller sideways and use the A or B buttons, like a real game controller.

**Comment by lvcabral** [comment]
Have you looked in the Settings Menu ? There is an option for that already implemented.
