### ISSUE TITLE
help with code

### ISSUE THREAD

**Issue by xoceunder** [lvcabral/Prince-of-Persia-Roku#46]
I see that you have enough knowledge want to see if you could help me with a problem I have in my Brightscript is I'm doing a style like netflix but the problem is that when entering the secion movie takes too long to get that slow loading and can not Select a movie to finish loading could help me with that problem.
@lvcabral

**Comment by lvcabral** [comment]
I don't think I understood the problem, but here is not the best place to raise this kind of questions. 
Please open a new thread at Roku Developers forum at:
http://forums.roku.com/viewforum.php?f=34
